#! /usr/bin/python3

# $ python3 -m venv ./sykno_py
# $ source ./sykno_py/bin/activate

# $ sudo docker build -f ./docker/Dockerfile -t sykno_docker . 
# sudo docker run -it --rm --privileged \
#     -e DISPLAY=$DISPLAY \
#     -v /dev/bus/usb:/dev/bus/usb \
#     -v /tmp/.X11-unix:/tmp/.X11-unix \
#     -v $(pwd)/mira/meas/hdf5/:/home/sykno/mira/meas/hdf5/ \
#     --hostname sykno-docker \
#     sykno_docker
    
# ==============================================================================
#                                  SYKNO CLI
# ==============================================================================
import __init__
import os
import click
import subprocess
import multiprocessing
from loguru import logger

@click.group()
def cli():
    pass


def check_activ_venv() -> bool:
    if 'VIRTUAL_ENV' in os.environ:
        try:
            if os.environ['VIRTUAL_ENV'].split('/')[-1] == 'sykno_env':
                logger.debug(f"Sykno MiRa Eval GUI is using {os.environ['VIRTUAL_ENV']} python venv")
                return True
            else:
                return False
        except:
            return False
    else:
        return False

def check_setup_venv():
    if os.path.isfile('./sykno_env/bin/activate'):
        logger.debug(f"Already setup sykno_env located: {os.path.abspath('./sykno_env')}")
        return
    else:
        logger.debug(f"Installing sykno_env in {os.path.abspath('./sykno_env')}")
        subprocess.run(['python3', '-m', 'venv', 'sykno_env'])
        logger.debug(f'Successfully created sykno_env.')
        
def start_mira_venv():
    """Start the virtual environment."""
    subprocess.run(['/bin/bash', './mira/setup/unix/start_mira_gui_venv.sh'])
    
@cli.command(help="This command starts the MiRa GUI application")
def start_mira():
    start_mira_process()

def start_mira_process():
    logger.debug("Starting MiRa GUI...")
    import multiprocessing
    import mira.gui.mira_eval_gui as mira_eval_gui

    mira_eval_gui_main_process = multiprocessing.Process(
        name='MiRa_Eval_GUI_Main_Process',
        target=mira_eval_gui.MIRA_MAIN_GUI.mira_gui_main, 
        args=())
    mira_eval_gui_main_process.daemon = False

    mira_eval_gui_main_process.start()
    mira_eval_gui_main_process.join()
    logger.debug("MiRa GUI started.")
        

# ==============================================================================
# Click Command Name: build
# ==============================================================================
@cli.command(help="TODO")
def setup_env():
    # logger.debug("Building Cython modules...")
    check_setup_venv()
    # logger.debug("Cython modules successfully built.")


# ==============================================================================
# Click Command Name: build
# ==============================================================================
@cli.command(help="This command builds the Cython modules for your Python3 version and CPU architecture")
def build():
    """
    Builds the Cython modules for the specified Python version and CPU architecture.

    This command invokes the setup.py script to compile the Cython modules.

    Example:
    python3 ./mira/proc/cython/setup.py build_ext --inplace
    """
    logger.debug("Building Cython modules...")
    subprocess.run(['python3', './mira/proc/cython/setup.py', 'build_ext', '--inplace'], check=True)
    subprocess.run(['python3', './mira/com/cython/setup.py', 'build_ext', '--inplace'], check=True)

    logger.debug("Successfully build cython modules.")


# ==============================================================================
# Click Command Name: mira_gui
# ==============================================================================
@cli.command(help="This command starts the MiRa GUI application")
def mira_gui():
    """
    Starts the MiRa GUI application.

    This command spawns a new process to run the MiRa GUI, allowing the main process to continue executing other tasks.

    Example:
    ./sykno_cli mira-gui
    """
    check_setup_venv()
    checker_venv = check_activ_venv()

    if checker_venv:
        # install_requirements()
        start_mira_process()
    else:
        start_mira_venv()


# Call the CLI as main to start Click access
if __name__ == '__main__':
    cli()
